function injectPurchaseStyles(){if(document.querySelector('#purchase-choice-styles'))return;const s=document.createElement('style');s.id='purchase-choice-styles';s.textContent='.details-link{display:inline-block;margin-top:9px;color:#2563eb;font-size:11px;font-weight:700}.purchase-choices{display:grid;gap:7px;margin-top:10px}.order-through-us,.amazon-direct{display:flex;align-items:center;justify-content:center;width:100%;min-height:38px;border:0;border-radius:999px;padding:9px 11px;font-size:11px;font-weight:800;cursor:pointer;text-align:center}.order-through-us{background:#ffb000;color:#111}.amazon-direct{background:#111827!important;color:#fff!important}.purchase-hint{font-size:9px;line-height:1.45;color:#7b8189;margin-top:7px}.result-card__main .details-link{margin-top:13px}.purchase-choices--list{min-width:190px}@media(max-width:760px){.purchase-choices--list{min-width:0}}';document.head.appendChild(s)}
function esc(v=''){return String(v).replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]))}
function sourceBadge(p){return `<span class="source-badge">${esc(marketplaceLabel(p))}</span>`}
function customsMini(p){return `<div style="margin-top:7px;font-size:10px;font-weight:800;color:#15803d">✓ Прошёл фильтр доставки и лимита</div>`}
function verificationMini(p){return `<div class="freshness-note">Проверено ${esc(formatCheckedDate(p.lastCheckedAt||STORE_META.generatedAt))}</div>`}
function sourcePriceBlock(p){if(p.priceUsd==null)return `<div class="to-ua">Цена до скидки</div><div class="price-line"><del>${formatUah(p.old)}</del></div><div class="saving">Скидка −${p.discount}%</div>`;const old=Number(p.listPriceUsd||p.priceUsd);return `<div class="to-ua">Цена на ${esc(marketplaceLabel(p))}</div><div style="display:flex;align-items:center;gap:8px;margin-top:3px;flex-wrap:wrap">${old>Number(p.priceUsd)?`<del style="color:#9ca3af;font-size:12px">${formatUsd(old)}</del>`:''}<strong style="font-size:18px">${formatUsd(p.priceUsd)}</strong><span style="background:#c2410c;color:#fff;border-radius:5px;padding:3px 6px;font-size:10px;font-weight:800">−${p.discount}%</span></div>`}
function externalCardLink(p){const url=externalPurchaseUrl(p);if(!url)return'';return `<a class="amazon-direct" href="${esc(url)}" target="_blank" rel="${externalPurchaseRel(p)}">Купить на ${esc(marketplaceLabel(p))} ↗</a>`}
function homeCard(p){return `<article class="deal-card"><div class="card-source">${sourceBadge(p)}</div><span class="sale-tag">−${p.discount}%</span><a class="deal-card__media" href="product.html?id=${p.id}"><img src="${esc(p.image)}" alt="${esc(p.brand+' '+p.name)}" loading="lazy"></a><h3><a href="product.html?id=${p.id}">${esc(p.brand+' '+p.name)}</a></h3><div class="rating">★ ${p.rating} · ${p.reviews.toLocaleString('ru-RU')} отзывов</div>${sourcePriceBlock(p)}<div class="to-ua" style="margin-top:8px">С доставкой в Украину через нас</div><div class="price-line"><strong>${formatUah(p.price)}</strong></div>${customsMini(p)}${verificationMini(p)}<a class="details-link" href="product.html?id=${p.id}">Подробнее о товаре</a><div class="purchase-choices"><button class="order-through-us branded-order" data-add="${p.id}" aria-label="Хапай сейл с нами" title="Хапай сейл с нами"><img class="order-brand-logo" src="hapai-sale-logo.png" alt="" aria-hidden="true" width="1974" height="797"><span class="order-brand-suffix">с нами</span></button>${externalCardLink(p)}</div><div class="purchase-hint">Через нас: выкуп + доставка + сервис. В магазине США: оплачиваете самостоятельно.</div></article>`}
function resultCard(p){return `<article class="result-card"><a class="result-card__media" href="product.html?id=${p.id}"><img src="${esc(p.image)}" alt="${esc(p.brand+' '+p.name)}" loading="lazy"></a><div class="result-card__main"><div class="result-card__brand">${sourceBadge(p)} ${esc(p.brand)}</div><h3><a href="product.html?id=${p.id}">${esc(p.name)}</a></h3><div class="rating">★ ${p.rating} · ${p.reviews.toLocaleString('ru-RU')} отзывов</div><div class="bought">Проверенная скидка · низкий риск доставки</div>${verificationMini(p)}<a class="details-link" href="product.html?id=${p.id}">Подробнее и расчёт цены</a></div><div class="result-card__buy">${sourcePriceBlock(p)}<div class="to-ua" style="margin-top:8px">С доставкой в Украину через нас</div><div class="price-line"><strong>${formatUah(p.price)}</strong></div>${customsMini(p)}<div class="purchase-choices purchase-choices--list"><button class="order-through-us branded-order" data-add="${p.id}" aria-label="Хапай сейл с нами" title="Хапай сейл с нами"><img class="order-brand-logo" src="hapai-sale-logo.png" alt="" aria-hidden="true" width="1974" height="797"><span class="order-brand-suffix">с нами</span></button>${externalCardLink(p)}</div><div class="purchase-hint">Покупка в магазине США оплачивается напрямую. Доставка через нас оформляется отдельным заказом.</div></div></article>`}
function bindAddButtons(){document.querySelectorAll('[data-add]').forEach(btn=>{const content=btn.innerHTML,label=btn.getAttribute('aria-label');let resetTimer;btn.onclick=()=>{addToCart(btn.dataset.add,1);clearTimeout(resetTimer);btn.textContent='Добавлено ✓';btn.setAttribute('aria-label','Добавлено в корзину');resetTimer=setTimeout(()=>{btn.innerHTML=content;if(label)btn.setAttribute('aria-label',label);else btn.removeAttribute('aria-label')},1000)}})}
function renderHome(){const grid=document.querySelector('#productGrid');if(!grid)return;if(!STORE_PRODUCTS.length){grid.innerHTML='<div class="empty-state">Сейчас нет товаров, которые проходят все наши условия по скидке, рейтингу, весу и лимиту.</div>';return}grid.innerHTML=[...STORE_PRODUCTS].sort((a,b)=>b.discount-a.discount||b.reviews-a.reviews).slice(0,12).map(homeCard).join('');bindAddButtons()}
function openModal(){document.querySelector('#modal')?.classList.add('open')}
function closeModal(){document.querySelector('#modal')?.classList.remove('open')}
document.querySelector('#requestBtn')?.addEventListener('click',openModal);document.querySelector('#requestBtn2')?.addEventListener('click',openModal);document.querySelector('#modalClose')?.addEventListener('click',closeModal);document.querySelector('#modal')?.addEventListener('click',e=>{if(e.target.id==='modal')closeModal()});
function searchStateText(meta,query){
  if(!query)return STORE_META.live?'Каталог получает данные из подключённого источника.':'Сейчас показываем вручную проверенный каталог. Цены подтверждаются перед выкупом.';
  if(meta?.mode==='remote')return `Поиск «${query}» выполнен по подключённым магазинам США. Наш фильтр уже применён.`;
  if(meta?.mode==='fallback')return `Поиск по магазинам временно недоступен. Показываем совпадения из последнего проверенного каталога.`;
  return `Сейчас поиск «${query}» идёт по нашему проверенному каталогу. Live-поиск по магазинам США включится после подключения серверного источника.`;
}
function renderCatalog(){
  const grid=document.querySelector('#catalogGrid');if(!grid)return;
  const sort=document.querySelector('#sortFilter'),categoryButtons=[...document.querySelectorAll('[data-cat]')],discRadios=[...document.querySelectorAll('input[name="disc"]')],priceRadios=[...document.querySelectorAll('input[name="price"]')],rating45=document.querySelector('#rating45'),headQ=document.querySelector('#headQ'),searchState=document.querySelector('#catalogSearchState');
  const params=new URLSearchParams(location.search);let activeCat=params.get('cat')||'all';let query=(params.get('q')||'').trim();let searchToken=0;
  if(headQ&&query)headQ.value=query;
  async function run(){
    const token=++searchToken;
    if(searchState)searchState.innerHTML=query?'<span class="search-spinner"></span> Ищем и фильтруем предложения...':searchStateText(null,'');
    let searchResult=query?await searchMarketplace(query,{category:activeCat}):{products:[...STORE_PRODUCTS],meta:{mode:'snapshot'}};
    if(token!==searchToken)return;
    let list=[...searchResult.products];
    if(activeCat!=='all')list=list.filter(p=>p.cat===activeCat);
    const disc=Number(document.querySelector('input[name="disc"]:checked')?.value||0);if(disc)list=list.filter(p=>p.discount>=disc);
    const maxPrice=Number(document.querySelector('input[name="price"]:checked')?.value||0);if(maxPrice)list=list.filter(p=>p.price<=maxPrice);
    if(rating45?.checked)list=list.filter(p=>p.rating>=4.5);
    if(sort?.value==='discount')list.sort((a,b)=>b.discount-a.discount||b.reviews-a.reviews);
    if(sort?.value==='rating')list.sort((a,b)=>b.rating-a.rating||b.reviews-a.reviews);
    if(sort?.value==='price-asc')list.sort((a,b)=>a.price-b.price);
    if(sort?.value==='price-desc')list.sort((a,b)=>b.price-a.price);
    grid.innerHTML=list.length?list.map(resultCard).join(''):`<div class="empty-state"><b>По этому запросу пока ничего не прошло наш фильтр.</b><br>Попробуйте более общий запрос или отправьте ссылку на конкретный товар.</div>`;
    const rt=document.querySelector('#resultsText');if(rt)rt.textContent=list.length?`${list.length} ${list.length===1?'товар':'товаров'}${query?` для «${query}»`:''}`:'0 товаров';
    if(searchState)searchState.textContent=searchStateText(searchResult.meta,query);
    bindAddButtons();categoryButtons.forEach(b=>b.classList.toggle('active',b.dataset.cat===activeCat));
  }
  categoryButtons.forEach(btn=>btn.addEventListener('click',()=>{activeCat=btn.dataset.cat;run()}));discRadios.forEach(el=>el.addEventListener('change',run));priceRadios.forEach(el=>el.addEventListener('change',run));rating45?.addEventListener('change',run);sort?.addEventListener('change',run);run();
}
document.addEventListener('DOMContentLoaded',async()=>{injectPurchaseStyles();await window.storeReady;renderHome();renderCatalog();syncCartBadges()});